@startmindmap
'https://plantuml.com/mindmap-diagram

title algorithm
* 总结
** 第一阶段
*** 算法
**** 位运算
***** 二级制及其基本位运算
***** 打印一个数的二进制形式
***** 不用中间变量交换两个数
***** 找到出现奇数的次数
***** 找出出现次数 K 次的数
***** N 皇后问题的加速实现
***** 位图
***** 位运算实现加、减、乘、除
**** 对数器
***** 随机行为
***** 对数器原理
**** 比较器
**** 排序算法
***** 选择
***** 冒泡
***** 插入
***** 归并
***** 快速
***** 堆
***** 计数
***** 基数
**** 二分及其扩展
***** 有序数组中查找数字
***** 有序数组查 >=num 最左的位置
***** 局部小值问题
**** 递归到动态规划
***** 递归行为
****** Master公式
****** 汉诺塔问题
****** 生成全子序列
****** 生成全排列
****** 大部分对数器方法

***** 动态规划

****** 从左往右尝试模型
******* 背包问题
******* 数字字符串转英文字符串
******* 贴纸问题
******* 货币找零方法的系列问题
******* 货币找零的最小张数问题
******* 累加和对半数组划分系列问题

****** 区间范围尝试模型
******* 纸牌游戏
******* 最长回文子序列

****** 样本对应尝试模型
******* 最长公共子序列
******* 最短路径和
******* Bob生存概率问题
******* 砍死怪兽概率问题
******* 分裂数学问题

****** 业务限制尝试次数
******* 机器人行进问题
******* 象棋跳马问题
******* 喝咖啡问题
******* N 皇后问题的加速实现

***** 贪心
****** 字典序的最小字符串连接方案
****** 点灯问题
****** 分金条问题
****** IPO 问题

*** 数据结构
**** 链表
**** 队列
**** 栈
**** 哈希表的使用
**** 有序表的使用
**** 堆
**** 加强堆
**** 前缀树
**** 二叉树
**** 并查集
**** 图
***** 图结构
***** 图算法
****** 拓扑排序
****** Kruskal 算法
****** Prim 算法
****** Dijkstra 算法
****** Dinic 算法
**** 哈夫曼树

** 第二阶段
*** 算法
**** 斐波那契数列
***** 矩阵乘法的解法
***** 有效的字符串数量
**** KMP 算法
***** 包含子树问题
***** 旋转字符串判断问题
**** Manacher 算法
***** 结尾添加字符变回文串
**** 无序数组寻找第 k 小的值
***** 改写快排
***** BFPRT 算法
**** 蓄水池算法
**** Morris 遍历
***** Morris 遍历求二叉树最小高度
**** 资源限制类题目的算法设计
**** 打表找规律
***** 小虎买苹果
***** 吃草问题
***** 连续数累加和判断
**** 根据题目数据量猜解法技巧
***** 贿赂怪兽问题
***** 分治
****** 累加和 %m 之后的最大值
****** 零食方法数问题
**** 卡特兰数
***** 1都不少于0的前缀串数量
***** 求不同二叉树数量
**** 数组三连
***** 窗口技巧（正数数组中累加和为给定值的最长子数组）
***** 预处理技巧（普通数组中累加和为给定值的最长子数组）
***** 淘汰可能性技巧（平均值 <=v 的最长子数组）
**** 状态压缩的动态规划
***** CanlWin 问题
***** TSP 问题
***** 贴瓷砖问题
**** 设计简化外部信息的动态规划
***** 打气球的最大分数
***** 消除箱子问题
***** 泡泡龙游戏
***** 奇怪的打印机
***** 数组的恢复方法
*** 数据结构
**** 窗口内最大值和最小值的更新结构
***** 特殊标准的子数组数量
***** 良好加油站的问题
***** 少找零张数进一步加速
***** 长度 <=M 子数组最大累加和
**** 单调栈
***** 累加和*最小值最大问题
***** 直方图内最大矩形
***** 全是1的最大矩形
***** 所有子数组的最小值累加
**** 线段树
***** 掉落瓷砖后的最大高度
**** IndexTree
**** AC 自动机
**** 和哈希函数有关的数据结构
***** 哈希表的原理和实现
***** 布隆过滤器的原理和实现
***** 一致性哈希原理和实现
**** 二维数组调整
***** 转圈打印矩阵
***** 翻转矩阵
***** zigzag 打印矩阵
***** 转圈打印星号
** 极致内容
*** 有序表
**** AVL 数的原理和实现
**** SB 树的原理和实现
**** 跳表的原理和实现
**** 各种有序表的对比
**** 改写有序表的相关题目
***** RangeSum 计数问题
***** 窗口中位数问题
***** 高效插入删除读取的数组
*** 四边形不等式
**** 区间划分问题中的不回退现象
**** 合并石子问题
**** 画匠问题
**** 邮局选址问题
**** 扔蛋问题
*** 后缀树DC3算法
**** 最大字典序的子串
**** 字符串插入得到的最大的字典序
**** 生成最大的数字
**** 最长公共子串
***** 动态规划的解
***** DC3 算法的解



@endmindmap
